environment:
  nuget_key:
    secure: Dntdq1e7oSujO0Yljz/xBP0fPf92Yy0RkAjA7RPRqFx4KMjqGzVXN5HBE9qE3esm
version: 1.0.{build}
branches:
  only:
  - master
skip_tags: true
image: WMF 5
install:
- ps: .\install.ps1
build_script:
- ps: .\build.ps1